server:
  port: 8284
  ssl:
    enabled: true
    keyStoreType: JKS
    key-alias: vdab
    key-store: /etc/ssl/certs/vdab.jks
    key-store-password: 3DHpdKDFVafErV7X

spring:
  application:
    name: gateway-server
  profiles:
    active: sand-box
  cloud:
    config:
      uri: https://sl01736v.ops.vdab.be:8888,https://sl01745v.ops.vdab.be:8888,https://sl01747v.ops.vdab.be:8888
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      # Configuration via declaration
      #  routes:
      #    - id: state-machine
      #      uri: lb://state-machine
      #predicates:
      # - Path=/api
      # config:
      # uri: ${CONFIG_URI:https://localhost:8888}

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: https://sl01748v.ops.vdab.be:8443/eureka,https://sl01749v.ops.vdab.be:8443/eureka,https://sl01750v.ops.vdab.be:8443/eurekas

# Security
vdab.key-store-certificate: /etc/ssl/certs/vdab.jks
vdab.key-store-password: 3DHpdKDFVafErV7X
vdab.trust-store-certificate: /etc/ssl/certs/vdab.jks
vdab.trust-store-password: 3DHpdKDFVafErV7X