server:
  port: 8284
  ssl:
    enabled: false
    keyStoreType: JKS
    key-alias: vdab
    key-store: /etc/ssl/certs/vdab.jks
    key-store-password: 3DHpdKDFVafErV7X

spring:
  application:
    name: gateway-server
  profiles:
    active: sand-box
  cloud:
    config:
      uri: http://sl01736v.ops.vdab.be:8888,http://sl01745v.ops.vdab.be:8888,http://sl01747v.ops.vdab.be:8888
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      # Configuration via declaration
      #routes:
      #- id: query-service
      #  uri: lb://query-service
      #  predicates:
      #  - Path=/query-service

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://sl01748v.ops.vdab.be:8443/eureka,http://sl01749v.ops.vdab.be:8443/eureka,http://sl01750v.ops.vdab.be:8443/eureka

# Security
vdab.key-store-certificate: /etc/ssl/certs/vdab.jks
vdab.key-store-password: 3DHpdKDFVafErV7X
vdab.trust-store-certificate: /etc/ssl/certs/vdab.jks
vdab.trust-store-password: 3DHpdKDFVafErV7X