server:
  port: 8284
  ssl:
    enabled: true
    keyStoreType: JKS
    key-alias: localhost
    key-store: /etc/ssl/certs/belgiantrain.jks
    key-store-password: password

spring:
  application:
    name: gateway-server
  profiles:
    active: default
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:https://localhost:8446/eureka}